// Geodesic math implementation matching apps/gov-dashboard/src/lib/geoUtils.js & droneWaypoints.js
const EARTH_RADIUS_KM = 6371;

function toRad(deg) {
  return (deg * Math.PI) / 180;
}

function toDeg(rad) {
  return (rad * 180) / Math.PI;
}

function computeDestination(lat, lng, bearing, distanceKm) {
  const d = distanceKm / EARTH_RADIUS_KM;
  const brng = toRad(bearing);
  const lat1 = toRad(lat);
  const lon1 = toRad(lng);

  const lat2 = Math.asin(
    Math.sin(lat1) * Math.cos(d) +
    Math.cos(lat1) * Math.sin(d) * Math.cos(brng)
  );

  const lon2 = lon1 + Math.atan2(
    Math.sin(brng) * Math.sin(d) * Math.cos(lat1),
    Math.cos(d) - Math.sin(lat1) * Math.sin(lat2)
  );

  return [toDeg(lat2), toDeg(lon2)];
}

function generateDroneWaypoints(lat, lng, footprint) {
  const bearing = footprint.bearing || 90;
  const lengthKm = Math.min(footprint.lengthKm || 10, 8.0);
  const spreadKm = Math.max((footprint.maxLateralSpreadKm || 2.0) * 0.4, 0.8);

  const leftBearing = (bearing - 90 + 360) % 360;
  const rightBearing = (bearing + 90) % 360;

  const [srcLeftLat, srcLeftLng] = computeDestination(lat, lng, leftBearing, spreadKm);
  const [srcRightLat, srcRightLng] = computeDestination(lat, lng, rightBearing, spreadKm);

  const [downLat, downLng] = computeDestination(lat, lng, bearing, lengthKm);
  const [downLeftLat, downLeftLng] = computeDestination(downLat, downLng, leftBearing, spreadKm * 1.5);
  const [downRightLat, downRightLng] = computeDestination(downLat, downLng, rightBearing, spreadKm * 1.5);

  const waypoints = [
    { id: 'WP-1', name: 'Source Intake Upwind Gate', lat: Math.round(srcLeftLat * 10000) / 10000, lng: Math.round(srcLeftLng * 10000) / 10000, altMeters: 120 },
    { id: 'WP-2', name: 'Downwind Core Traversal Left', lat: Math.round(downLeftLat * 10000) / 10000, lng: Math.round(downLeftLng * 10000) / 10000, altMeters: 180 },
    { id: 'WP-3', name: 'Downwind Core Traversal Right', lat: Math.round(downRightLat * 10000) / 10000, lng: Math.round(downRightLng * 10000) / 10000, altMeters: 180 },
    { id: 'WP-4', name: 'Source Perimeter Return Gate', lat: Math.round(srcRightLat * 10000) / 10000, lng: Math.round(srcRightLng * 10000) / 10000, altMeters: 120 }
  ];

  const generateKml = (incidentTitle = 'VesperAero Drone Flight Plan') => `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${incidentTitle} - UAV Survey Grid</name>
    <description>Autonomous plume perimeter patrol waypoints generated by VesperAero</description>
    ${waypoints
      .map(
        (wp) => `
    <Placemark>
      <name>${wp.id}: ${wp.name}</name>
      <description>Altitude: ${wp.altMeters}m AGL</description>
      <Point>
        <coordinates>${wp.lng},${wp.lat},${wp.altMeters}</coordinates>
      </Point>
    </Placemark>`
      )
      .join('\n')}
  </Document>
</kml>`;

  const generateGpx = (incidentTitle = 'VesperAero Flight Plan') => `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="VesperAero UAV Dispatcher" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${incidentTitle}</name>
    <time>${new Date().toISOString()}</time>
  </metadata>
  <rte>
    <name>Plume Core Autonomous Survey</name>
    ${waypoints
      .map(
        (wp) => `
    <rtept lat="${wp.lat}" lon="${wp.lng}">
      <ele>${wp.altMeters}</ele>
      <name>${wp.id}</name>
      <desc>${wp.name}</desc>
    </rtept>`
      )
      .join('\n')}
  </rte>
</gpx>`;

  return { waypoints, generateKml, generateGpx };
}

describe('VesperAero Autonomous UAV/Drone Survey Waypoint Engine', () => {
  const originLat = 31.634;
  const originLng = 74.872;
  const mockFootprint = {
    bearing: 90,
    lengthKm: 14.5,
    maxLateralSpreadKm: 3.2
  };

  test('1. Computes 4 perimeter flight waypoints enclosing the toxic core', () => {
    const flightPlan = generateDroneWaypoints(originLat, originLng, mockFootprint);
    expect(flightPlan).toBeDefined();
    expect(Array.isArray(flightPlan.waypoints)).toBe(true);
    expect(flightPlan.waypoints.length).toBe(4);

    const [wp1, wp2, wp3, wp4] = flightPlan.waypoints;
    expect(wp1.id).toBe('WP-1');
    expect(wp2.id).toBe('WP-2');
    expect(wp3.id).toBe('WP-3');
    expect(wp4.id).toBe('WP-4');
    expect(wp1.altMeters).toBe(120);
    expect(wp2.altMeters).toBe(180);
  });

  test('2. Generates standard KML XML string for DJI / Google Earth', () => {
    const flightPlan = generateDroneWaypoints(originLat, originLng, mockFootprint);
    const kml = flightPlan.generateKml('Stubble Fire Patrol');
    expect(kml).toContain('<?xml version="1.0" encoding="UTF-8"?>');
    expect(kml).toContain('<kml xmlns="http://www.opengis.net/kml/2.2">');
    expect(kml).toContain('<name>WP-1: Source Intake Upwind Gate</name>');
    expect(kml).toContain('Stubble Fire Patrol');
  });

  test('3. Generates standard GPX XML string for ArduPilot / Mission Planner', () => {
    const flightPlan = generateDroneWaypoints(originLat, originLng, mockFootprint);
    const gpx = flightPlan.generateGpx('Stubble Fire Patrol');
    expect(gpx).toContain('<?xml version="1.0" encoding="UTF-8"?>');
    expect(gpx).toContain('<gpx version="1.1"');
    expect(gpx).toContain('<rtept lat=');
    expect(gpx).toContain('<name>WP-2</name>');
  });
});
