import { computeDestination } from './geoUtils';

/**
 * Generates autonomous UAV/Drone survey waypoints surrounding the high-concentration plume core
 * @param {number} lat - Emission source latitude
 * @param {number} lng - Emission source longitude
 * @param {Object} footprint - Plume footprint containing bearing, lengthKm, and maxLateralSpreadKm
 * @returns {Object} Waypoints and KML/GPX generator methods
 */
export function generateDroneWaypoints(lat, lng, footprint) {
  const bearing = footprint.bearing || 90;
  const lengthKm = Math.min(footprint.lengthKm || 10, 8.0); // Core survey boundary (max 8km for battery limits)
  const spreadKm = Math.max((footprint.maxLateralSpreadKm || 2.0) * 0.4, 0.8);

  // Compute 4 box corner points
  const leftBearing = (bearing - 90 + 360) % 360;
  const rightBearing = (bearing + 90) % 360;

  // Source-side corners
  const [srcLeftLat, srcLeftLng] = computeDestination(lat, lng, leftBearing, spreadKm);
  const [srcRightLat, srcRightLng] = computeDestination(lat, lng, rightBearing, spreadKm);

  // Downwind-side center and corners
  const [downLat, downLng] = computeDestination(lat, lng, bearing, lengthKm);
  const [downLeftLat, downLeftLng] = computeDestination(downLat, downLng, leftBearing, spreadKm * 1.5);
  const [downRightLat, downRightLng] = computeDestination(downLat, downLng, rightBearing, spreadKm * 1.5);

  const waypoints = [
    { id: 'WP-1', name: 'Source Intake Upwind Gate', lat: Math.round(srcLeftLat * 10000) / 10000, lng: Math.round(srcLeftLng * 10000) / 10000, altMeters: 120 },
    { id: 'WP-2', name: 'Downwind Core Traversal Left', lat: Math.round(downLeftLat * 10000) / 10000, lng: Math.round(downLeftLng * 10000) / 10000, altMeters: 180 },
    { id: 'WP-3', name: 'Downwind Core Traversal Right', lat: Math.round(downRightLat * 10000) / 10000, lng: Math.round(downRightLng * 10000) / 10000, altMeters: 180 },
    { id: 'WP-4', name: 'Source Perimeter Return Gate', lat: Math.round(srcRightLat * 10000) / 10000, lng: Math.round(srcRightLng * 10000) / 10000, altMeters: 120 }
  ];

  const generateKml = (incidentTitle = 'VesperAero Drone Flight Plan') => `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${incidentTitle} - UAV Survey Grid</name>
    <description>Autonomous plume perimeter patrol waypoints generated by VesperAero</description>
    ${waypoints
      .map(
        (wp) => `
    <Placemark>
      <name>${wp.id}: ${wp.name}</name>
      <description>Altitude: ${wp.altMeters}m AGL</description>
      <Point>
        <coordinates>${wp.lng},${wp.lat},${wp.altMeters}</coordinates>
      </Point>
    </Placemark>`
      )
      .join('\n')}
    <Placemark>
      <name>Survey Flight Perimeter</name>
      <LineString>
        <tessellate>1</tessellate>
        <coordinates>
          ${waypoints.map((wp) => `${wp.lng},${wp.lat},${wp.altMeters}`).join(' ')} ${waypoints[0].lng},${waypoints[0].lat},${waypoints[0].altMeters}
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`;

  const generateGpx = (incidentTitle = 'VesperAero Flight Plan') => `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="VesperAero UAV Dispatcher" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${incidentTitle}</name>
    <time>${new Date().toISOString()}</time>
  </metadata>
  <rte>
    <name>Plume Core Autonomous Survey</name>
    ${waypoints
      .map(
        (wp) => `
    <rtept lat="${wp.lat}" lon="${wp.lng}">
      <ele>${wp.altMeters}</ele>
      <name>${wp.id}</name>
      <desc>${wp.name}</desc>
    </rtept>`
      )
      .join('\n')}
  </rte>
</gpx>`;

  return {
    waypoints,
    generateKml,
    generateGpx
  };
}
